name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull cristianortizheano/target-manager:latest
    - name: Delete Old docker container
      run: sudo docker rm -f target-manager-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8081:8081 --name target-manager-container cristianortizheano/target-manager:latest