name: CI Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USER_ORTIZ}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD_ORTIZ}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build jar
        env:
          JAR_FILE: ${{vars.JAR_FILE}}
        run: mvn package -Dmaven.test.skip

      - name: Build docker image
        run: docker build --build-arg JAR_FILE=$JAR_FILE -t target-manager .

      - name: Push to Dockerhub
        run: |
          docker tag target-manager:latest cristianortizheano/target-manager:latest
          docker push cristianortizheano/target-manager:latest
